config/routes.rb
# frozen_string_literal: true

require 'rswag/ui/engine'

Rails.application.routes.draw do
  get 'election_sheet_candidates/new'
  get 'election_sheet_candidates/destroy'

  get 'elections/' => 'elections#current'
  get 'elections/recent' => 'elections#recent'
  get 'elections/current' => 'elections#current'
  get 'elections/upcoming' => 'elections#upcoming'

  resources :election_sheets, only: %i[new destroy] do
    member do
      post :vote, to: 'election_sheet_user_votes#create'
    end
  end
  resources :election_sheet_candidates, only: %i[new destroy]

  root to: 'welcome#index'

  resources :welcome, only: %i[index]

  resources :user_groups, :groups, :roles
  resources :elections do
    member do
      get :pdf_preview
      get :pdf
      get :vote
      get :results
    end
  end

  authenticate :user, ->(u) { u.role.name == 'admin' } do
    mount Rswag::Ui::Engine, at: '/api-docs'
    mount Rswag::Api::Engine, at: '/api-docs'
  end

  devise_for :users
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group, only: %i[ show edit update destroy ]

  # GET /user_groups or /user_groups.json
  def index
    @user_groups = UserGroup.all
    authorize @user_groups
  end

  # GET /user_groups/1 or /user_groups/1.json
  def show
    authorize @user_group
  end

  # GET /user_groups/new
  def new
    @user_group = UserGroup.new
    authorize @user_group
  end

  # GET /user_groups/1/edit
  def edit
    authorize @user_group
  end

  # POST /user_groups or /user_groups.json
  def create
    @user_group = UserGroup.new(user_group_params)

    authorize @user_group

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to user_group_url(@user_group), notice: "User group was successfully created." }
        format.json { render :show, status: :created, location: @user_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_groups/1 or /user_groups/1.json
  def update
    authorize @user_group

    respond_to do |format|
      if @user_group.update(user_group_params)
        format.html { redirect_to user_group_url(@user_group), notice: "User group was successfully updated." }
        format.json { render :show, status: :ok, location: @user_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1 or /user_groups/1.json
  def destroy
    authorize @user_group

    @user_group.destroy!

    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: "User group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_group_params
    params.require(:user_group).permit(:user_id, :group_id)
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_with(model: user_group, class: "contents") do |form| %>
  <% if user_group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>

      <ul>
        <% user_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%=
      form.select(
        :user_id,
        User.order(:email).map { |u| [u.email, u.id] },
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
      )
    %>
  </div>

  <div class="my-5">
    <%= form.label :group_id %>
    <%=
      form.select(
        :group_id,
        Group.order(:name).map { |u| [u.name, u.id] },
        class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
      )
    %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_groups/_user_group.html.erb
<div id="<%= dom_id user_group %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= user_group.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Group:</strong>
    <%= user_group.group_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user group", user_group, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this user group", edit_user_group_path(user_group), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/user_groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user group</h1>

  <%= render "form", user_group: @user_group %>

  <%= link_to "Show this user group", @user_group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to user groups", user_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_groups/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">User groups</h1>
    <%= link_to "New user group", new_user_group_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="user_groups" class="min-w-full">
    <%= render @user_groups %>
  </div>
</div>

app/views/user_groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user group</h1>

  <%= render "form", user_group: @user_group %>

  <%= link_to "Back to user groups", user_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user_group %>

    <%= link_to "Edit this user_group", edit_user_group_path(@user_group), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user_group", user_group_path(@user_group), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to user_groups", user_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>