config/routes.rb
# frozen_string_literal: true

require 'rswag/ui/engine'

Rails.application.routes.draw do
  get 'election_sheet_candidates/new'
  get 'election_sheet_candidates/destroy'

  get 'elections/' => 'elections#current'
  get 'elections/recent' => 'elections#recent'
  get 'elections/current' => 'elections#current'
  get 'elections/upcoming' => 'elections#upcoming'

  resources :election_sheets, only: %i[new destroy] do
    member do
      post :vote, to: 'election_sheet_user_votes#create'
    end
  end
  resources :election_sheet_candidates, only: %i[new destroy]

  root to: 'welcome#index'

  resources :welcome, only: %i[index]

  resources :user_groups, :groups, :roles
  resources :elections do
    member do
      get :pdf_preview
      get :pdf
      get :vote
      get :results
    end
  end

  authenticate :user, ->(u) { u.role.name == 'admin' } do
    mount Rswag::Ui::Engine, at: '/api-docs'
    mount Rswag::Api::Engine, at: '/api-docs'
  end

  devise_for :users
end

app/models/election.rb
class Election < ApplicationRecord
  has_many :election_groups, dependent: :delete_all
  has_many :election_sheets, dependent: :destroy
  has_many :election_sheet_candidates, through: :election_sheets
  has_many :groups, through: :election_groups
  has_many :users, through: :groups
  has_many :election_sheet_user_votes, through: :election_sheets

  accepts_nested_attributes_for :election_sheets
end

app/controllers/elections_controller.rb
class ElectionsController < ApplicationController
  before_action :set_election, only: %i[edit update destroy vote results]

  def index
    @elections ||= Election.all

    authorize @elections
  end


  def recent
    dt_now = DateTime.now

    @elections = Election.where(date_to: ..dt_now)
    @highlighted_item = 1

    authorize @elections

    render :index
  end

  def current
    dt_now = DateTime.now

    @elections = Election.where(date_from: ..dt_now, date_to: dt_now..)
    @highlighted_item = 2
    
    authorize @elections

    render :index
  end
  def upcoming
    dt_now = DateTime.now

    @elections = Election.where(date_from: dt_now..)
    @highlighted_item = 3

    authorize @elections

    render :index
  end

  def new
    @election = Election.new
    @election.election_sheets.build.election_sheet_candidates.build

    authorize @election
  end

  def create
    @election = Election.new(election_params)

    authorize @election

    respond_to do |format|
      if @election.save
        format.html { redirect_to elections_path, notice: 'Pomyślnie utworzono wybory.' }
        format.json { render :index, status: :created, location: @election }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @election = Election.find(params[:id])

    authorize @election
  end

  def update
    @election = Election.find(params[:id])

    authorize @election

    respond_to do |format|
      if @election.update(election_params)
        format.html { redirect_to elections_path, notice: 'Pomyślnie zaktualizowano wybory.' }
        format.json { render :index, status: :created, location: @election }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @election.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @election = Election.find(params[:id])

    authorize @election
    if @election.destroy
      redirect_to elections_path, notice: 'Pomyślnie usunięto wybory.'
    else
      redirect_to elections_path, alert: 'Nie udało się usunąć wyborów.'
    end
  end

  def vote
    authorize @election
  end

  def results
    authorize @election

  end

  def pdf_preview
    @election = Election.eager_load(:election_sheets, :election_sheet_user_votes, :election_sheet_candidates).find(params[:id])

    authorize @election

    render 'elections/pdf', layout: false
  end

  def pdf
    @election = Election.eager_load(:election_sheets, :election_sheet_user_votes, :election_sheet_candidates).find(params[:id])

    authorize @election

    pdf_str = render_to_string pdf: "some_file_name", template: "elections/pdf", encoding: "UTF-8" , dpi: 300, zoom: 1.1285

    send_data pdf_str,
              filename: "document.pdf",
              type: "application/pdf",
              disposition: "inline",
              dpi: 300

    #redirect_to("data:application/pdf;base64,#{Base64.strict_encode64(pdf_str)}", allow_other_host: true )
  end


  private

  def set_election
    @election = Election.find(params[:id])
    @user = current_user
  end

  def election_params
    params.require(:election).permit(
      :name,
      :description,
      :date_from,
      :date_to,
      group_ids: [],
      election_sheets_attributes: [
        :id,
        :name,
        :description,
        :max_votes_per_user,
        :max_votes_per_candidate,
        :requires_all_votes_spent,
        { election_sheet_candidates_attributes: %i[id name] }
      ]
    )
  end
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/views/elections/_election_fields.html.erb
<div class="my-5">
  <%= form.label :name, 'Nazwa' %>
  <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

<div class="my-5">
  <%= form.label :description, 'Opis' %>
  <%= form.text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full min-h-[120px] max-h-64" %>
</div>

<div class="my-5">
  <%= form.label :date_from, 'Czas rozpoczęcia wyborów' %>
  <%= form.datetime_field :date_from, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>
<div class="my-5">
  <%= form.label :date_to, 'Czas zakończenia wyborów' %>
  <%= form.datetime_field :date_to, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

app/views/elections/_election_groups_fields.html.erb
<legend class="font-bold text-4xl">
  Grupy
</legend>

<div class="my-5 bg-white shadow rounded-md border border-gray-200 py-2 flex flex-col">
  <%= form.collection_check_boxes :election_group_ids, Group.order(:name), :id, :name do |g| %>
    <div>
      <%= g.check_box %>
      <%= g.label %>
    </div>
  <% end %>
</div>

app/views/elections/_form.html.erb
<%= form_with(model: election, data: { controller: "render-response" }, class: "contents") do |form| %>
  <% if election.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(election.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
        <% election.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend class="font-bold text-4xl">
      <% is_edit ||= false %>
      <%= is_edit ? "Edycja wyborów o id: #{election.id.to_s}" : 'Nowe wybory' %>
    </legend>
    <%= render 'election_fields', form: form %>
  </fieldset>

  <br/>

  <fieldset>
    <legend class="font-bold text-4xl">Grupy</legend>
    <%= render 'group_fields', form: form %>
  </fieldset>

  <br/>

  <!-- KARTY WYBORÓW -->
  <div>
    <div id="election_sheets">
      <%= render partial: 'election_sheets/election_sheet', collection: @election.election_sheets %>
    </div>

    <%=
      link_to(
        "Dodaj Kartę",
        new_election_sheet_path,
        data: { turbo_stream: true },
        class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"
      )
    %>
  </div>

  <br/>

  <div class="inline">
    <%= form.submit 'Zapisz', class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/elections/_group_fields.html.erb
<div class="my-5 bg-white shadow rounded-md border border-gray-200 py-2 flex flex-col max-h-[18.125rem] overflow-y-auto overflow-x-hidden" id="groups-container">
  <div class="pt-2 pb-4">
    <input type="text" class="w-4/5" placeholder="Wyszukaj grupę..." id="groups-container-searchbar">
  </div>
  <%= form.collection_check_boxes :group_ids, Group.order(:name), :id, :name do |g| %>
    <div class="grid grid-cols-6 gap-x-4 group" data-group-name="<%= g.object.name %>">
      <%= g.check_box class: "col-span-1 justify-self-end align-middle self-center"%>
      <%= g.label class: "col-span-5 text-start align-middle"%>
    </div>
  <% end %>
</div>

<script>
    const groupsContainer = document.getElementById('groups-container');
    const searchbar = document.getElementById('groups-container-searchbar');
    const groups = groupsContainer.getElementsByClassName('group');

    searchbar.addEventListener('input', () => {
        const searchValue = searchbar.value.toLowerCase();

        if(!searchValue)
        {
            Array.from(groups).forEach(el => el.classList.remove('hidden'));
        }
        else
        {
            Array.from(groups).forEach(el => {
                const matching = fuzzysearch(
                  searchValue,
                  el.getAttribute('data-group-name').toLowerCase()
                );

                matching ? el.classList.remove('hidden') : el.classList.add('hidden')
            })
        }
    });


    // Thank You https://github.com/bevacqua/fuzzysearch

    // The MIT License (MIT)
    //
    // Copyright © 2015 Nicolas Bevacqua
    //
    // Permission is hereby granted, free of charge, to any person obtaining a copy of
    // this software and associated documentation files (the "Software"), to deal in
    // the Software without restriction, including without limitation the rights to
    // use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
    // the Software, and to permit persons to whom the Software is furnished to do so,
    //   subject to the following conditions:
    //
    //   The above copyright notice and this permission notice shall be included in all
    // copies or substantial portions of the Software.
    //
    //   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    // IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
    // FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
    // COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
    // IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
    // CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

    function fuzzysearch (needle, haystack) {
        var hlen = haystack.length;
        var nlen = needle.length;
        if (nlen > hlen) {
            return false;
        }
        if (nlen === hlen) {
            return needle === haystack;
        }
        outer: for (var i = 0, j = 0; i < nlen; i++) {
            var nch = needle.charCodeAt(i);
            while (j < hlen) {
                if (haystack.charCodeAt(j++) === nch) {
                    continue outer;
                }
            }
            return false;
        }
        return true;
    }

</script>

app/views/elections/_sheets_result.html.erb
<%= turbo_frame_tag dom_id(election_sheet) do %>
  <% total_voters_eligible = election_sheet.election.users.distinct.count %>
  <% voters = election_sheet.election_sheet_user_votes.count %>
  <% total_votes_on_candidates = election_sheet.election_sheet_candidates.sum(:votes) %>
  <div class="my-5 relative bg-white shadow rounded-md border border-gray-200 p-4 flex flex-col justify-center gap-y-4">
    <h3 class="m-0 p-0">Karta </h3>

    <h4 class="m-0 p-0"><%= election_sheet.name %></h4>

    <p><%= election_sheet.description %></p>

    <span>Do wykorzystania: <span><%= election_sheet.max_votes_per_user %></span> głosów.</span>
    <span>Maksymalna ilość głosów na kandydata: <span><%= election_sheet.max_votes_per_candidate %></span> głosów.</span>
    <% if election_sheet.requires_all_votes_spent %>
      <span>Wymagane było wydanie wszystkich głosów</span>
    <% end %>

    <span>
      Frekwencja w ramach tej karty wynosi:
      <b><%= number_to_percentage(100 * voters / total_voters_eligible.to_d, precision: 2) %></b>
    </span>

    <div class="grid grid-cols-12 gap-y-2 gap-x-1">
      <div class="col-span-4 text-left font-bold pb-2">
        Kandydat
      </div>
      <div class="col-span-2 text-left font-bold pb-2">
        Głosy
      </div>
      <div class="col-span-6 text-left font-bold pb-2 text-center">
        Procent
      </div>
      <% election_sheet.election_sheet_candidates.order(votes: :desc).each do |candidate| %>
        <% percent = (100.0 * candidate.votes / total_votes_on_candidates).to_d %>
        <div class="col-span-4 text-left">
          <%= candidate.name %>
        </div>
        <div class="col-span-2 text-left">
          <%= candidate.votes %>
        </div>
        <div class="col-span-2 text-right">
          <b><%= number_to_percentage(percent, precision: 2) %></b>
        </div>
        <div class="col-span-4 flex flex-row justify-start">
          <div class="h-8 bg-green-100 border border-green-300 hover:bg-green-200 " style="width: <%= percent %>%"></div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/elections/_vote_sheet.html.erb
<%= turbo_frame_tag dom_id(election_sheet) do %>
  <div class="my-5 relative bg-white shadow rounded-md border border-gray-200 p-4 flex flex-col justify-center gap-y-4">
    <% if sheet_has_been_voted %>
      <div class="w-full h-full absolute top-0 left-0 z-999 bg-white bg-opacity-60 grid items-center text-center text-3xl font-bold">
        Oddano głos
      </div>
    <% end %>
    <h3 class="m-0 p-0">Karta nr. <%= index + 1 %></h3>

    <h4 class="m-0 p-0"><%= election_sheet.name %></h4>

    <p><%= election_sheet.description %></p>

    <span>Do wykorzystania: <span><%= election_sheet.max_votes_per_user %></span> głosów.</span>
    <span>Maksymalna ilość głosów na kandydata: <span><%= election_sheet.max_votes_per_candidate %></span> głosów.</span>
    <% if election_sheet.requires_all_votes_spent %>
      <span>Wymagane jest wydanie wszystkich głosów</span>
    <% end %>

    <% unless validation_error.zero? %>
      <p class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 ">
        <% case validation_error
          when 1 %>
            Wydano w sumie więcej głosów niż <%= election_sheet.max_votes_per_user %>
          <% when 2 %>
            Wydano więcej głosów na jednego kandydata niż <%= election_sheet.max_votes_per_candidate %>
          <% when 3 %>
            Należy wydać dokładnie <%= election_sheet.max_votes_per_user %> głosów
        <% end %>
      </p>
    <% end %>

    <%= form_with(url: vote_election_sheet_path(election_sheet), class: 'py-2') do |form| %>
      <div class="my-4">
        <% election_sheet.election_sheet_candidates.each do |candidate| %>
          <div class="flex justify-between gap-x-4 my-4 w-4/5">
            <%= candidate.name %>
            <%= form.hidden_field :election_candidate_id, value: candidate.id, multiple: true %>
            <%= form.number_field :votes, min: 0, class: "form-input", multiple: true %>
          </div>
        <% end %>
      </div>
      <% if sheet_has_been_voted %>
        <div class="h-16 w-full"></div>
      <% else %>
        <%= form.submit "Oddaj głos w tej karcie", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
      <%  end %>
    <% end %>
  </div>
<% end %>

app/views/elections/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Elections#create</h1>
  <p>Find me in app/views/elections/create.html.erb</p>
</div>

app/views/elections/edit.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <%= render "form", election: @election, is_edit: true %>
    <%=
      link_to(
        "Powrót do listy wyborów",
        elections_path,
        class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium",
        data: { turbo_frame: "new_elections_frame" }
      )
    %>
  </div>
<% end %>

app/views/elections/index.html.erb
<%= turbo_frame_tag "content" do %>
  <% if policy(Election).index? %>

    <h3>Lista wyborów</h3>

    <div class="w-full grid grid grid-cols-3 bg-white border-gray-300">
      <%= link_to(
            'Zeszłe',
            elections_recent_path,
            class: "py-6 col-span-1 hover:bg-gray-100 #{@highlighted_item == 1 ? 'bg-gray-100' : ''}",
      )%>
      <%= link_to(
            'Aktualne',
            elections_current_path,
            class: "py-6 col-span-1 hover:bg-gray-100 #{@highlighted_item == 2 ? 'bg-gray-100' : ''}",
      )%>
      <%= link_to(
            'Przyszłe',
            elections_upcoming_path,
            class: "py-6 c  ol-span-1 hover:bg-gray-100 #{@highlighted_item == 3 ? 'bg-gray-100' : ''}",
      )%>
    </div>
    <div class="pt-4">
      <div class="my-5 bg-white shadow rounded-md border border-gray-200 max-h-[30rem] overflow-x-visible overflow-y-auto pb-2 px-4 w-full grid grid-cols-12 gap-x-2 gap-y-2 min-h-6">
        <div class="border-b-2 border-gray col-span-12 grid grid-cols-12 py-2 font-bold">
          <div class="col-span-2 flex flex-row justify-start">
            ID
          </div>
          <div class="col-span-6 flex flex-row justify-start min-h-6">
            Nazwa
          </div>
          <div class="col-span-4 flex flex-row justify-center min-h-6 ">
            Akcje
          </div>
        </div>
        <% if @elections.exists? %>
          <% @elections.each do |e| %>
            <% can_vote = policy(e).vote? %>
            <div class="col-span-2 flex flex-row justify-start self-center">
              <%= e.id %>
            </div>
            <div class="<%= can_vote ? 'col-span-4' : 'col-span-6' %> flex flex-row justify-start self-center">
              <%= e.name %>
            </div>
            <div class="<%= can_vote ? 'col-span-6' : 'col-span-4' %> flex flex-row justify-around self-center">
              <% if policy(e).results? %>
                <%= link_to results_election_path(id: e.id) do %>
                  <i class="fa-xl fa-solid fa-square-poll-horizontal" title="Wyniki"></i>
                <% end %>
              <% end %>
              <% if policy(e).pdf? %>
                <%= link_to pdf_election_path(id: e.id), data: {turbo: false}  do %>
                  <i class="fa-xl fa-solid fa-file-pdf" title="Wyniki PDF"></i>
                <% end %>
              <% end %>
              <% if can_vote %>
                <%= link_to vote_election_path(id: e.id) do %>
                  <i class="fa-xl fa-solid fa-check-to-slot" title="Głosowanie"></i>
                <% end %>
              <% end %>
              <% if policy(Election).new? %>
                <%= link_to edit_election_path(id: e.id) do %>
                  <i class="fa-xl fa-solid fa-pen-to-square" title="Edycja"></i>
                <% end %>
              <% end %>
              <% if policy(Election).destroy? %>
                <%= button_to e, method: :delete do %>
                  <i class="fa-xl fa-solid fa-trash" style="color: #000000;" title="Usunięcie"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="col-span-12 flex flex-row justify-center text-gray italic">
            Brak
          </div>
        <% end %>
      </div>
    </div>
    <% if policy(Election).new? %>
      <%=
        link_to(
          "Nowe wybory",
          new_election_path,
          class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium",
          data: { turbo_frame: "new_elections_frame" }
        )
      %>
    <% end %>
  <% end %>
<% end %>

app/views/elections/new.html.erb
<%= turbo_frame_tag "content" do %>
  <div class="mx-auto md:w-2/3 w-full">
    <%= render "form", election: @election, is_edit: false %>
    <%=
      link_to(
        "Powrót do listy wyborów",
        elections_path,
        class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium",
        data: { turbo_frame: "new_elections_frame" }
      )
    %>
  </div>
<% end %>

app/views/elections/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= wicked_pdf_stylesheet_link_tag "tailwind" -%>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <style>
      *
      {
        -webkit-print-color-adjust: exact;
      }
      html
      {
          padding: 0 !important;
      }
      html, body
      {
          width: 210mm;
      }
      body
      {
          margin:0 !important;
      }
      .nobreak
      {
          page-break-inside: avoid;
      }
      .nobreak:before
      {
          clear:both;
      }
  </style>
</head>
  <body class="flex flex-col text-center">
    <div class="w-1/2 ml-auto pb-8">
      <div class="text-right pb-2">
        <span class="block font-bold">
          Data wygenerowania:
        </span>
        <span class="block">
          <%= DateTime.now.to_s %>
        </span>
      </div>
      <div class="text-right pb-2">
        <span class="block font-bold">
          SHA-256:
        </span>
        <span class="block">
          <% sha_str = Digest::SHA256.hexdigest @election.to_json %>
          <span><%= sha_str[0...32] %></span>
          <span><%= sha_str[32..-1] %></span>
        </span>
      </div>
    </div>

    <h1><b>Wyniki głosowania</b></h1>
    <h3><i><%= @election.name %></i></h3>

    <div>
      <% @election.election_sheets.each do |election_sheet| %>
        <% total_voters_eligible = election_sheet.election.users.distinct.count %>
        <% voters = election_sheet.election_sheet_user_votes.count %>
        <% total_votes_on_candidates = election_sheet.election_sheet_candidates.sum(:votes) %>
        <div class="nobreak my-5 relative bg-white rounded-md flex flex-col justify-center pt-8">
          <h3 class="m-0 p-0"><b>Karta do głosowania</b></h3>

          <h4 class="m-0 p-0"><i><%= election_sheet.name %></i></h4>

          <p><%= election_sheet.description %></p>
          <br/>

          <span>Do wykorzystania: <span><%= election_sheet.max_votes_per_user %></span> głosów.</span><br/>
          <span>Maksymalna ilość głosów na kandydata: <span><%= election_sheet.max_votes_per_candidate %></span> głosów.</span><br/>
          <% if election_sheet.requires_all_votes_spent %>
            <span>Wymagane było wydanie wszystkich głosów</span><br/>
          <% end %>
          <br/>

          <span>
          Frekwencja w ramach tej karty wynosi:
          <b><%= number_to_percentage(100 * voters / total_voters_eligible.to_d, precision: 2) %></b><br/>
          Jest to <b><%= voters %></b> głosujących z <b><%= total_voters_eligible %></b> uprawnionych do głosowania
          </span>
          <br/>
          <span>Łącznie oddano <b><%= total_votes_on_candidates %></b> głosów na kandydatów</span>
          <br/>
          <br/>

          <table class="w-full">
            <thead>
            <tr>
              <th class="p-2">Nr.</th>
              <th class="p-2">Kandydat</th>
              <th class="p-2">Głosy</th>
              <th class="p-2">Procent</th>
            </tr>
            </thead>
            <tbody>
            <% election_sheet.election_sheet_candidates.order(votes: :desc).each_with_index do |candidate, index| %>
              <% percent = (100.0 * candidate.votes / total_votes_on_candidates).to_d %>
              <% row_bg = index % 2 == 0 ? 'background-color: #efefef !important;' : ''%>
              <tr>
                <td class="p-2" style="<%= row_bg %>"><%= index + 1%></td>
                <td class="p-2" style="<%= row_bg %>"><%= candidate.name %></td>
                <td class="p-2" style="<%= row_bg %>"><%= candidate.votes %></td>
                <td class="p-2" style="<%= row_bg %>"><%= number_to_percentage(percent, precision: 2) %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/elections/results.html.erb
<%= turbo_frame_tag "content" do %>
  <h2>Głosowanie</h2>
  <h3><%= @election.name %></h3>

  <div>
    <% @election.election_sheets.each do |election_sheet| %>
      <%= render(
            partial: 'elections/sheets_result',
            locals: { election_sheet: }
          )
      %>
    <% end %>
  </div>

  <%=
    link_to(
      "Powrót do listy wyborów",
      elections_path,
      class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium",
      data: { turbo_frame: "new_elections_frame" }
    )
  %>

<% end %>

app/views/elections/vote.html.erb
<%= turbo_frame_tag "content" do %>
  <h2>Głosowanie</h2>
  <h3><%= @election.name %></h3>

  <div>
    <% @election.election_sheets.each_with_index do |election_sheet, index| %>
      <% sheet_has_been_voted = election_sheet.election_sheet_user_votes.exists?(user_id: @user.id) %>
        <%= render(
            partial: 'elections/vote_sheet',
            locals: {
              election_sheet: election_sheet,
              index: index,
              sheet_has_been_voted: sheet_has_been_voted,
              validation_error: 0
            }
        )
        %>
    <% end %>
    </div>

    <%=
      link_to(
        "Powrót do listy wyborów",
        elections_path,
        class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium",
        data: { turbo_frame: "new_elections_frame" }
      )
    %>

<% end %>